import json
import asyncio
from typing import Any, Dict, Optional
from jsonschema import validate, ValidationError
from confluent_kafka import Producer

class KafkaProducerService:
    def __init__(self, bootstrap_servers: str, extra_config: Optional[Dict[str, Any]] = None):
        config = {'bootstrap.servers': bootstrap_servers}
        if extra_config:
            config.update(extra_config)
        self.producer = Producer(config)

    def validate_message(self, message: Dict[str, Any], schema: Dict[str, Any]) -> None:
        """
        Validates the message against the provided JSON Schema.
        """
        try:
            validate(instance=message, schema=schema)
        except ValidationError as e:
            raise ValueError(f"Invalid message generated by LLM: {e.message}") from e

    def _delivery_report(self, err, msg):
        """
        Delivery callback for Kafka Producer.
        """
        if err is not None:
            # Here you could use structlog, but simple print/raise for now or just log
            print(f"Message delivery failed: {err}")
        else:
            print(f"Message delivered to {msg.topic()} [{msg.partition()}]")

    def _produce_sync(self, topic: str, message_bytes: bytes) -> None:
        self.producer.produce(topic, message_bytes, callback=self._delivery_report)
        self.producer.poll(0) # Trigger callbacks
        self.producer.flush() # Ensure it's sent

    async def produce_message(self, topic: str, message: Dict[str, Any], payload_schema: Optional[Dict[str, Any]] = None) -> None:
        """
        Asynchronously produces a message to the specified topic, optionally validating it first.
        """
        if payload_schema:
            self.validate_message(message, payload_schema)

        message_bytes = json.dumps(message).encode('utf-8')

        loop = asyncio.get_running_loop()
        await loop.run_in_executor(None, self._produce_sync, topic, message_bytes)

    def close(self):
        self.producer.flush()
