import re
import json
from typing import Any, Dict, Optional
import httpx
from jsonschema import validate, ValidationError
from jsonpath_ng import parse

class VaultSecretFetcher:
    """Mock-хранилище секретов"""
    def __init__(self, secrets: Dict[str, str] = None):
        self._secrets = secrets or {}

    def get_secret(self, key: str) -> Optional[str]:
        return self._secrets.get(key)

class RestApiClient:
    def __init__(self, vault: Optional[VaultSecretFetcher] = None):
        self.vault = vault or VaultSecretFetcher()
        self.client = httpx.AsyncClient()

    async def close(self):
        await self.client.aclose()

    def validate_arguments(self, parameters: Dict[str, Any], schema: Dict[str, Any]) -> None:
        """
        Реализовать валидацию аргументов, сгенерированных LLM, через parameters_schema инструмента.
        """
        try:
            validate(instance=parameters, schema=schema)
        except ValidationError as e:
            raise ValueError(f"Invalid arguments generated by LLM: {e.message}") from e

    def interpolate_template(self, template: str, params: Dict[str, Any]) -> str:
        """
        Реализовать интерполяцию шаблонов (вставка параметров в URL или тело запроса).
        """
        # Supports formats like {param_name}
        def replace(match):
            key = match.group(1)
            if key in params:
                return str(params[key])
            return match.group(0) # leave untouched if not found

        return re.sub(r'\{([^}]+)\}', replace, template)

    def inject_secrets(self, headers: Dict[str, str], auth_config: Optional[Dict[str, Any]]) -> Dict[str, str]:
        """
        Разработать механизм получения секретов (из Vault или мок-хранилища) для подстановки в заголовки авторизации.
        """
        processed_headers = dict(headers) if headers else {}

        if not auth_config:
            return processed_headers

        auth_type = auth_config.get("type")
        if auth_type == "bearer":
            secret_key = auth_config.get("secret_key")
            if secret_key:
                secret_value = self.vault.get_secret(secret_key)
                if secret_value:
                    processed_headers["Authorization"] = f"Bearer {secret_value}"
        elif auth_type == "api_key":
            header_name = auth_config.get("header_name", "X-API-Key")
            secret_key = auth_config.get("secret_key")
            if secret_key:
                secret_value = self.vault.get_secret(secret_key)
                if secret_value:
                    processed_headers[header_name] = secret_value

        return processed_headers

    def extract_with_jsonpath(self, data: Any, jsonpath_expr: str) -> Any:
        """
        Написать логику извлечения данных из большого ответа REST API с использованием JSONPath для экономии контекста (токенов).
        """
        if not jsonpath_expr:
            return data

        try:
            jsonpath_expression = parse(jsonpath_expr)
            matches = [match.value for match in jsonpath_expression.find(data)]

            if not matches:
                return None
            if len(matches) == 1:
                return matches[0]
            return matches
        except Exception as e:
            raise ValueError(f"Error applying JSONPath expression '{jsonpath_expr}': {str(e)}") from e

    async def execute(self,
                      method: str,
                      base_url: str,
                      endpoint: str,
                      parameters: Dict[str, Any],
                      parameters_schema: Optional[Dict[str, Any]] = None,
                      headers: Optional[Dict[str, str]] = None,
                      auth_config: Optional[Dict[str, Any]] = None,
                      body_template: Optional[Any] = None,
                      jsonpath_filter: Optional[str] = None) -> Any:

        # 1. Валидация
        if parameters_schema:
            self.validate_arguments(parameters, parameters_schema)

        # 2. Интерполяция URL
        url = base_url.rstrip("/") + "/" + endpoint.lstrip("/")
        url = self.interpolate_template(url, parameters)

        # 3. Подготовка заголовков и секретов
        request_headers = self.inject_secrets(headers or {}, auth_config)

        # 4. Формирование тела запроса/параметров (простая реализация для примера)
        kwargs = {}
        if method.upper() in ["GET", "DELETE"]:
            # Если параметры не были использованы в URL, возможно, это query params.
            # В более сложной реализации можно разделить параметры пути и параметры запроса по схеме.
            # Здесь просто передаем все параметры.
            kwargs["params"] = parameters
        else:
            if body_template:
                if isinstance(body_template, str):
                    body = self.interpolate_template(body_template, parameters)
                    try:
                        kwargs["json"] = json.loads(body)
                    except json.JSONDecodeError:
                        kwargs["data"] = body
                elif isinstance(body_template, dict):
                    # Для dict делаем строковую интерполяцию JSON-представления
                    body_str = json.dumps(body_template)
                    body_str = self.interpolate_template(body_str, parameters)
                    kwargs["json"] = json.loads(body_str)
            else:
                kwargs["json"] = parameters

        # 5. Вызов
        response = await self.client.request(method, url, headers=request_headers, **kwargs)
        response.raise_for_status()

        try:
            response_data = response.json()
        except ValueError:
            response_data = response.text

        # 6. JSONPath фильтрация
        if jsonpath_filter and isinstance(response_data, (dict, list)):
            return self.extract_with_jsonpath(response_data, jsonpath_filter)

        return response_data
