import pytest
import json
from unittest.mock import MagicMock, patch
from app.services.kafka import KafkaProducerService

@pytest.fixture
def mock_producer():
    with patch('app.services.kafka.Producer') as MockProducer:
        yield MockProducer

@pytest.mark.asyncio
async def test_produce_message_success(mock_producer):
    service = KafkaProducerService(bootstrap_servers="localhost:9092")

    topic = "test_topic"
    message = {"key": "value", "id": 123}
    schema = {
        "type": "object",
        "properties": {
            "key": {"type": "string"},
            "id": {"type": "integer"}
        },
        "required": ["key", "id"]
    }

    # Should not raise any exception
    await service.produce_message(topic, message, schema)

    # Assert produce was called with correct arguments
    producer_instance = mock_producer.return_value
    assert producer_instance.produce.called

    args, kwargs = producer_instance.produce.call_args
    assert args[0] == topic
    assert json.loads(args[1].decode('utf-8')) == message

    # Assert flush was called
    assert producer_instance.flush.called

@pytest.mark.asyncio
async def test_produce_message_validation_error(mock_producer):
    service = KafkaProducerService(bootstrap_servers="localhost:9092")

    topic = "test_topic"
    message = {"key": 123} # Invalid type for key
    schema = {
        "type": "object",
        "properties": {
            "key": {"type": "string"}
        },
        "required": ["key"]
    }

    with pytest.raises(ValueError) as excinfo:
        await service.produce_message(topic, message, schema)

    assert "Invalid message generated by LLM" in str(excinfo.value)

    # Producer should NOT be called
    producer_instance = mock_producer.return_value
    assert not producer_instance.produce.called

@pytest.mark.asyncio
async def test_produce_message_no_schema(mock_producer):
    service = KafkaProducerService(bootstrap_servers="localhost:9092")

    topic = "test_topic"
    message = {"unvalidated": "data"}

    # Should not raise any exception
    await service.produce_message(topic, message)

    producer_instance = mock_producer.return_value
    assert producer_instance.produce.called
