import pytest
from app.services.rest_api import RestApiClient, VaultSecretFetcher
import httpx
from unittest.mock import AsyncMock, patch, MagicMock
import json

@pytest.fixture
def vault():
    return VaultSecretFetcher({"api_key": "secret_api_key_123"})

@pytest.fixture
def client(vault):
    return RestApiClient(vault=vault)

@pytest.mark.asyncio
async def test_validate_arguments(client):
    schema = {
        "type": "object",
        "properties": {
            "name": {"type": "string"},
            "age": {"type": "integer"}
        },
        "required": ["name", "age"]
    }

    # Valid
    client.validate_arguments({"name": "Test", "age": 20}, schema)

    # Invalid type
    with pytest.raises(ValueError, match="Invalid arguments generated by LLM"):
        client.validate_arguments({"name": "Test", "age": "twenty"}, schema)

    # Missing required
    with pytest.raises(ValueError, match="Invalid arguments generated by LLM"):
        client.validate_arguments({"name": "Test"}, schema)

def test_interpolate_template(client):
    template = "https://api.example.com/users/{user_id}/posts/{post_id}"
    params = {"user_id": 123, "post_id": 456, "extra": "data"}

    interpolated = client.interpolate_template(template, params)
    assert interpolated == "https://api.example.com/users/123/posts/456"

def test_inject_secrets_bearer(client):
    headers = {"Content-Type": "application/json"}
    auth_config = {"type": "bearer", "secret_key": "api_key"}

    new_headers = client.inject_secrets(headers, auth_config)
    assert new_headers["Content-Type"] == "application/json"
    assert new_headers["Authorization"] == "Bearer secret_api_key_123"

def test_inject_secrets_api_key(client):
    headers = {"Content-Type": "application/json"}
    auth_config = {"type": "api_key", "header_name": "X-Custom-Key", "secret_key": "api_key"}

    new_headers = client.inject_secrets(headers, auth_config)
    assert new_headers["Content-Type"] == "application/json"
    assert new_headers["X-Custom-Key"] == "secret_api_key_123"

def test_extract_with_jsonpath(client):
    data = {
        "users": [
            {"id": 1, "name": "Alice"},
            {"id": 2, "name": "Bob"}
        ],
        "meta": {"total": 2}
    }

    # Extract single list
    names = client.extract_with_jsonpath(data, "$.users[*].name")
    assert names == ["Alice", "Bob"]

    # Extract single value
    total = client.extract_with_jsonpath(data, "$.meta.total")
    assert total == 2

    # Extract not found
    empty = client.extract_with_jsonpath(data, "$.meta.count")
    assert empty is None

@pytest.mark.asyncio
async def test_execute_rest_api_call(client):
    method = "GET"
    base_url = "https://api.example.com"
    endpoint = "/users/{user_id}"
    parameters = {"user_id": 42}
    schema = {"type": "object", "properties": {"user_id": {"type": "integer"}}}

    # Mock httpx.AsyncClient.request
    with patch.object(client.client, 'request', new_callable=AsyncMock) as mock_request:
        # Mocking the response itself using a regular mock since its methods are synchronous
        # (except json or text, we need to mock json)
        mock_response = MagicMock()
        mock_response.json.return_value = {"id": 42, "name": "Test User"}
        mock_response.raise_for_status.return_value = None

        mock_request.return_value = mock_response

        result = await client.execute(
            method=method,
            base_url=base_url,
            endpoint=endpoint,
            parameters=parameters,
            parameters_schema=schema,
            jsonpath_filter="$.name"
        )

        assert result == "Test User"
        mock_request.assert_called_once_with(
            "GET",
            "https://api.example.com/users/42",
            headers={},
            params={"user_id": 42}
        )
